replicaCount: 1

image:
  repository: komall6/node-bulletin-board
  tag: "v2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000    # match Node.js app port

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: bulletin.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
